// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vims_Webapi.Model;

#nullable disable

namespace Vims_Webapi.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20220712142459_final")]
    partial class final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Vims_Webapi.Model.Claim", b =>
                {
                    b.Property<int>("claim_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("claim_id"), 1L, 1);

                    b.Property<int>("claim_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("claim_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("custid")
                        .HasColumnType("int");

                    b.Property<int>("policyid")
                        .HasColumnType("int");

                    b.Property<int>("vehid")
                        .HasColumnType("int");

                    b.HasKey("claim_id");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("Vims_Webapi.Model.Customer", b =>
                {
                    b.Property<int>("custid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("custid"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_no")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("custid");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("Vims_Webapi.Model.payment_info", b =>
                {
                    b.Property<int>("pay_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pay_id"), 1L, 1);

                    b.Property<int>("custid")
                        .HasColumnType("int");

                    b.Property<int>("paid_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("policyid")
                        .HasColumnType("int");

                    b.HasKey("pay_id");

                    b.ToTable("payment_info");
                });

            modelBuilder.Entity("Vims_Webapi.Model.policy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("custid")
                        .HasColumnType("int");

                    b.Property<decimal>("gst_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("policyid")
                        .HasColumnType("int");

                    b.Property<decimal>("premium_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("renew_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("vehid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("policy");
                });

            modelBuilder.Entity("Vims_Webapi.Model.renew_policy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("Initial_policy_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("Next_renew_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("custid")
                        .HasColumnType("int");

                    b.Property<decimal>("gst_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("renew_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("vehid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("renew_policy");
                });

            modelBuilder.Entity("Vims_Webapi.Model.Vehicle_info", b =>
                {
                    b.Property<int>("vehid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehid"), 1L, 1);

                    b.Property<string>("Veh_engine_no")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("custid")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("purchase_year")
                        .HasColumnType("int");

                    b.Property<string>("regi_no")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("veh_chassis_no")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("vehid");

                    b.ToTable("vehicle_info");
                });
#pragma warning restore 612, 618
        }
    }
}
